### ISSUE TITLE
Cast to usize triggers ``Instruction not yet implemented: Unknown`` in device firmware

### ISSUE THREAD

**Issue by francois141** [CharlyCst/miralis#178] opened 2024-09-02 09:04 UTC
It looks like there is another bug found by the test device..... @CharlyCst :)

### Step to reproduce the bug

```bash
git checkout test-device-usize-illegal; cargo run --package runner -- run --config {{qemu_virt_release}} --firmware device
```

#### Logs

```bash
[Info  | miralis] Hello, world!
[Info  | miralis] Platform name: QEMU virt
[Info  | miralis] Hart ID: 0
[Info  | miralis] misa:    0x80000000001411ad
[Info  | miralis] vmisa:   0x8000000000141101
[Info  | miralis] mstatus: 0xa00000000
[Info  | miralis] DTS address: 0x87e00000
[Info  | miralis] Preparing jump into firmware
[Info  | miralis::virt] > Hello from driver tester firmware!
[Error | miralis] Panicked at PanicInfo {
    payload: Any { .. },
    message: Some(
        not yet implemented: Instruction not yet implemented: Unknown,
    ),
    location: Location {
        file: "src/virt.rs",
        line: 490,
        col: 18,
    },
    can_unwind: true,
    force_no_backtrace: false,
} 
[Info  | miralis::debug] Maximal stack usage: 5616 bytes (17.71%)
```

**Comment by CharlyCst** [comment] 2024-09-02 11:29
It is an `lwu`, "load word unsigned". Raw assembly is ` 0x56583`.

I can reproduce it with you branch, but not on `main`. I think the bug was fixed by @Wesdcv during her load/store refactoring which got merged recently.

I will close the issue, but feel free to re-open if the issue turns out not to be resolved.

**Closed by CharlyCst** 2024-09-02 11:29 UTC
Labels: bug
